deploymentConfig:
  # The organisation name of your deployment repo
  org: pizzeria-ristorante
  # The repostiory name of your deployment repo
  repository: ristorante-deployment-config
  # The name of the application that is used in your deployment repo
  applicationName: menu-service

previewConfig:
  route:
    host:
      # your router host.
      #{SHA256_8CHAR_BRANCH_HASH} gets replaced by a shortened hash of your feature branch name
      template: menu-service-{SHA256_8CHAR_BRANCH_HASH}.apps.okd.baloise.dev
  replace:
    # Paths that should be replaced
    - path: menu-service.image.tag
      variable: GIT_COMMIT # this is the latest git hash of the PR branch
    - path: menu-service.ingress.host
      variable: ROUTE_HOST # this is the resolved SHA256_8CHAR_BRANCH_HASH from above